### ISSUE TITLE
Ошибка авто реактов

### ISSUE THREAD

**Issue by MrLivixx** [vladciphersky/sonata#5]
Если поставить кастомный эмодзи для авто реакта то бот не ставит

**Comment by vladciphersky** [comment]
• Найденный баг: отсутствие возможности установить в **s.react** кастомный эмодзи
• Баг-хантер: @MrLivixx 
• От разработчика: подтверждено, найден ещё баг: отсутствие проверки прав (на наличие администратора)

**Comment by vladciphersky** [comment]
Придётся перекопать весь код. Пока-что **s.react** не работает.
За то пофиксил права для pv и react, а ещё отключение приват. войсов в pv.js
